### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '../../token2vec/chemdner_pubmed_biov5_drug.token4_d100'

### ISSUE THREAD

**Issue by nlp-wh** [lingluodlut/JointBioER#1]
师兄好！我是隔壁海事的学生：）在调试您联合学习代码的时候出现如下错误："FileNotFoundError: [Errno 2] No such file or directory: '../../token2vec/chemdner_pubmed_biov5_drug.token4_d100'"，应该是缺少必要的预训练词嵌入，请问您是否方便提供一下相关的词嵌入文件呢？万分感谢！

**Comment by lingluodlut** [comment]
你好，由于时间比较久了，原来的词向量文件我没找到，你可以自己用word2vec工具训练一个。
